# Generated by Django 3.2.9 on 2021-12-12 14:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug_name', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('path', models.CharField(blank=True, max_length=100)),
                ('ports', models.CharField(blank=True, max_length=100)),
                ('container_id', models.CharField(blank=True, max_length=30)),
                ('created_at', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, choices=[('STOPPED', 'STOPPED'), ('CREATED', 'CREATED'), ('STARTING', 'STARTING'), ('STOPPING', 'STOPPING'), ('STARTED', 'STARTED'), ('DISABLED', 'DISABLED')], max_length=30)),
                ('current_status', models.CharField(blank=True, max_length=30)),
                ('container_name', models.CharField(blank=True, max_length=30)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('command', models.CharField(blank=True, max_length=100)),
                ('is_docker_compose', models.BooleanField(default=False)),
                ('lab_details', models.TextField(blank=True)),
                ('docker_compose_file', models.FileField(blank=True, upload_to=app.models.folder_path)),
            ],
        ),
    ]
